//
// Created by root on 10/19/25.
//

#ifndef TOURNAMENTS_ERROR_HPP
#define TOURNAMENTS_ERROR_HPP

enum class Error
{
    NOT_FOUND,
    DUPLICATE,
    INVALID_FORMAT,
    UNKNOWN_ERROR,
    UNPROCESSABLE_ENTITY
};

#endif //TOURNAMENTS_ERROR_HPP